name: Build and Release EXE

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate date version
        id: version
        shell: pwsh
        run: |
          $currentDate = Get-Date -Format "yyyy-MM-dd"
          echo "VERSION=$currentDate" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka ordered-set zstandard
          pip install playwright
        
      - name: Build EXE with Nuitka
        run: |
          python -m nuitka --onefile --enable-plugin=playwright --output-filename=start.exe main.py

      - name: Move output
        run: |
          mkdir dist
          mv start.exe dist/start.exe

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v_${{ env.VERSION }}"
          name: "Release v_${{ env.VERSION }}"
          body: |
            âœ… Auto Release Build
            ðŸ“… Version: v_${{ env.VERSION }}
          files: dist/start.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
