name: Build and Release EXE

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Nuitka Compiler Cache
        uses: actions/cache@v4
        with:
          path: ${{ env.LOCALAPPDATA }}/Nuitka
          key: nuitka-cache

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ${{ env.LOCALAPPDATA }}/pip/Cache
          key: pip-cache

      - name: Generate date version
        id: version
        shell: pwsh
        run: |
          $currentDate = Get-Date -Format "yyyy-MM-dd"
          echo "VERSION=$currentDate" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Update version in config.json
        shell: pwsh
        run: |
          $jsonPath = "config.json"
          $config = Get-Content $jsonPath | ConvertFrom-Json
          $config.version = $env:VERSION
          $config | ConvertTo-Json -Depth 10 | Set-Content $jsonPath -Encoding utf8

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka ordered-set zstandard

      - name: Build EXE with Nuitka
        run: |
          nuitka main.py --onefile --clang --lto=yes --output-dir=dist --assume-yes-for-downloads --output-filename=start.exe 

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v_${{ env.VERSION }}"
          name: "Release v_${{ env.VERSION }}"
          body: |
            âœ… Auto Release Build
            ðŸ“… Version: v_${{ env.VERSION }}
          files: start.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

