name: Build and Release EXE

on:
  workflow_dispatch:
  push:
    branches: ["dev"]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate date version
        id: version
        shell: pwsh
        run: |
          $currentDate = Get-Date -Format "yyyy-MM-dd"
          echo "VERSION=$currentDate" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Update version in config.json
        shell: pwsh
        run: |
          $jsonPath = "config.json"
          $config = Get-Content $jsonPath | ConvertFrom-Json
          $config.version = $env:VERSION
          $config | ConvertTo-Json -Depth 10 | Set-Content $jsonPath -Encoding utf8

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller==5.13.2
          playwright install --with-deps msedge
          
      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --name start --distpath dist --exclude-module playwright._driver.chromium main.py

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v_${{ env.VERSION }}"
          name: "Release v_${{ env.VERSION }}"
          body: |
            âœ… Auto Release Build
            ðŸ“… Version: v_${{ env.VERSION }}
          files: dist/start.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}